version: "2"
linters:
  default: standard
  exclusions:
    paths:
      - integration/s3-test/s3-tests
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
  exclusions:
    paths:
      - integration/s3-test/s3-tests
