version: "3"

tasks:
  default:
    desc: "Display this help message"
    cmds:
      - task -l

  lint:
    desc: "Lint"
    cmds:
      - golangci-lint run --fix
      - golangci-lint fmt

  test:
    desc: "Test"
    cmds:
      - richgo test -v -shuffle=on -race ./...
      - task: sdk

  sdk:
    desc: "Integration test (AWS SDK)"
    dir: integration/sdk
    cmds:
      - richgo test -v -shuffle=on -race ./...

  s3test:
    desc: "Integration test (s3-tests)"
    dir: integration/s3-test
    cmds:
      - docker compose up --build --abort-on-container-exit
