version: "3"

tasks:
  default:
    desc: "Display this help message"
    cmds:
      - task -l

  lint:
    desc: "Lint"
    cmds:
      - golangci-lint run --fix
      - golangci-lint fmt

  test:
    desc: "Test"
    cmds:
      - task: unit-test
      - task: sdk-test
      - task: s3-test

  unit-test:
    desc: "Unit test"
    cmds:
      - richgo test -v -shuffle=on -race ./...

  sdk-test:
    desc: "SDK test"
    dir: integration/sdk
    cmds:
      - richgo test -v -shuffle=on -race ./...

  s3-test:
    desc: "ceph/s3-tests test"
    dir: integration/s3-test
    cmds:
      - docker compose up --build --abort-on-container-exit
