FROM golang:1.25-alpine AS builder
ENV GOTOOLCHAIN=auto
WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY internal ./internal
COPY integration/s3-test/main.go ./integration/s3-test/
RUN CGO_ENABLED=0 go build -o minis3 ./integration/s3-test

FROM alpine:3.23@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659
RUN apk add --no-cache wget
COPY --from=builder /app/minis3 /usr/local/bin/
EXPOSE 9000
CMD ["minis3", "-addr", "0.0.0.0:9000"]
