FROM python:3.14-slim@sha256:5b3879b6f3cb77e712644d50262d05a7c146b7312d784a18eff7ff5462e77033

WORKDIR /s3-tests
COPY s3-tests/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY s3-tests/ .
COPY s3tests.conf /s3tests.conf
COPY sitecustomize.py /s3-tests/sitecustomize.py
COPY conftest.py /s3-tests/conftest.py

ENV S3TEST_CONF=/s3tests.conf

ENTRYPOINT ["pytest", "-v", "--tb=short", "s3tests/functional/test_s3.py"]
