FROM golang:1.26-alpine@sha256:70b46548e42db77e0966aaf3619fd068734dc6c77584d526b91126504fd95816 AS builder
ENV GOTOOLCHAIN=auto
WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY internal ./internal
COPY integration/s3-test/main.go ./integration/s3-test/
RUN CGO_ENABLED=0 go build -o minis3 ./integration/s3-test

FROM alpine:3.24@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
RUN apk add --no-cache wget
COPY --from=builder /app/minis3 /usr/local/bin/
EXPOSE 9000
CMD ["minis3", "-addr", "0.0.0.0:9000"]
