FROM python:3.14-slim@sha256:486b8092bfb12997e10d4920897213a06563449c951c5506c2a2cfaf591c599f

WORKDIR /s3-tests
COPY s3-tests/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY s3-tests/ .
COPY s3tests.conf /s3tests.conf
COPY sitecustomize.py /s3-tests/sitecustomize.py
COPY conftest.py /s3-tests/conftest.py

ENV S3TEST_CONF=/s3tests.conf

ENTRYPOINT ["pytest", "-v", "--tb=short", "s3tests/functional/test_s3.py"]
