FROM python:3.14-slim@sha256:44dd04494ee8f3b538294360e7c4b3acb87c8268e4d0a4828a6500b1eff50061

WORKDIR /s3-tests
COPY s3-tests/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY s3-tests/ .
COPY s3tests.conf /s3tests.conf
COPY sitecustomize.py /s3-tests/sitecustomize.py
COPY conftest.py /s3-tests/conftest.py

ENV S3TEST_CONF=/s3tests.conf

ENTRYPOINT ["pytest", "-v", "--tb=short", "s3tests/functional/test_s3.py"]
